CREATE TABLE PRINT_CONFIG_PC (
  ID_PRINT_CONFIG_PC NUMBER ,
  DADO BLOB NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  TIPO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_PRINT_CONFIG_PC)
);

CREATE TABLE TRILHA (
  ID_TRILHA NUMBER ,
  DESCRICAO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_TRILHA)
);

CREATE TABLE LINGUAGEM (
  ID_LINGUAGEM NUMBER ,
  NOME VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_LINGUAGEM)
);

CREATE TABLE EDICAO (
  ID_EDICAO NUMBER,
  NOME VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_EDICAO)
);

CREATE TABLE CURRICULO (
  ID_CURRICULO NUMBER ,
  DADO BLOB NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  TIPO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_CURRICULO)
);

CREATE TABLE CARGO (
  ID_CARGO NUMBER ,
  NOME VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_CARGO)
);

CREATE TABLE GESTOR (
  ID_GESTOR NUMBER,
  NOME VARCHAR2(255) NOT NULL,
  EMAIL VARCHAR2(255) NOT NULL,
  SENHA VARCHAR2(255) NOT NULL,
  ATIVO CHAR(1) NOT NULL,
  GENERO CHAR(1) NOT NULL,
  CIDADE VARCHAR2(255) NOT NULL,
  ESTADO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_GESTOR)
);

CREATE TABLE GESTOR_CARGO (
  ID_CARGO NUMBER NOT NULL,
  ID_GESTOR NUMBER NOT NULL,
  CONSTRAINT FK_GEST_CAR_ID_GEST
    FOREIGN KEY (ID_GESTOR)
      REFERENCES GESTOR(ID_GESTOR),
  CONSTRAINT FK_GEST_CAR_ID_CARG
    FOREIGN KEY (ID_CARGO)
      REFERENCES CARGO(ID_CARGO)
);

CREATE TABLE FORMULARIO (
  ID_FORMULARIO NUMBER ,
  ID_CURRICULO NUMBER NOT NULL,
  ID_TRILHA NUMBER NOT NULL,
  ID_PRINT_CONFIG_PC NUMBER NOT NULL,
  INSTITUICAO VARCHAR2(255) NOT NULL,
  LGPD CHAR(1) NOT NULL,
  GITHUB VARCHAR2(255),
  LINKEDIN VARCHAR2(255),
  DESAFIOS CHAR(1) NOT NULL,
  PROBLEMAS CHAR(1) NOT NULL,
  RECONHECIMENTO CHAR(1) NOT NULL,
  ALTRUISMO CHAR(1) NOT NULL,
  RESPOSTA VARCHAR2(255) ,
  TURNO VARCHAR2(255) NOT NULL,
  PROVA CHAR(1),
  INGLES VARCHAR2(20) NOT NULL,
  ESPANHOL VARCHAR2(20) NOT NULL,
  NEURODIVERSIDADE VARCHAR2(255),
  CONFIG_PC VARCHAR2(255) NOT NULL,
  EFETIVACAO CHAR(1) NOT NULL,
  DISPONIBILIDADE CHAR(1) NOT NULL,
  GENERO VARCHAR2(30) NOT NULL,
  ORIENTACAO VARCHAR2(30) NOT NULL,
  MATRICULA CHAR(1) NOT NULL,
  CURSO VARCHAR2(255) NOT NULL,
  INSPIRACAO VARCHAR2(255) NOT NULL,
  IMPORTANCIA_TI VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_FORMULARIO)
);

CREATE TABLE CANDIDATO (
  ID_CANDIDATO  NUMBER,
  ID_FORMULARIO NUMBER NOT NULL,
  ID_EDICAO NUMBER NOT NULL,
  EMAIL VARCHAR2(255) NOT NULL,
  TELEFONE VARCHAR2(30) NOT NULL,
  RG VARCHAR2(30) NOT NULL,
  CPF VARCHAR2(30) NOT NULL,
  ESTADO VARCHAR2(50) NOT NULL,
  CIDADE VARCHAR2 (255) NOT NULL,
  PCD CHAR(1) NOT NULL,
  OBSERVACOES VARCHAR2(255),
  NOTA_COMPORTAMENTAL NUMBER,
  NOTA_TECNICA NUMBER,
  NOTA_PROVA NUMBER,
  ATIVO CHAR(1) NOT NULL,
  MEDIA NUMBER,
  PRIMARY KEY (ID_CANDIDATO),
  CONSTRAINT FK_CAND_ID_ED
    FOREIGN KEY (ID_EDICAO)
      REFERENCES EDICAO(ID_EDICAO)
);

CREATE TABLE LINGUAGEM_CANDIDATO (
  ID_LINGUAGEM NUMBER ,
  ID_CANDIDATO NUMBER NOT NULL,
  CONSTRAINT FK_LING_CAND_ID_LING
    FOREIGN KEY (ID_LINGUAGEM)
      REFERENCES LINGUAGEM(ID_LINGUAGEM),
  CONSTRAINT FK_LING_CAND_ID_CAND
    FOREIGN KEY (ID_CANDIDATO)
      REFERENCES CANDIDATO(ID_CANDIDATO)
);

CREATE TABLE INSCRICAO (
  ID_INSCRICAO NUMBER ,
  ID_CANDIDATO NUMBER NOT NULL,
  DATA_INSCRICAO DATE NOT NULL,
  AVALIADO CHAR(1) NOT NULL,
  PRIMARY KEY (ID_INSCRICAO)
);

CREATE TABLE AVALIACAO (
  ID_AVALIACAO NUMBER ,
  ID_INSCRICAO NUMBER NOT NULL,
  ID_GESTOR NUMBER NOT NULL,
  APROVADO CHAR(1) NOT NULL,
  PRIMARY KEY (ID_AVALIACAO),
  CONSTRAINT FK_AVA_ID_GEST
    FOREIGN KEY (ID_GESTOR)
      REFERENCES GESTOR(ID_GESTOR)
);

CREATE TABLE ENTREVISTAS (
  ID_ENTREVISTA NUMBER,
  ID_GESTOR NUMBER NOT NULL,
  ID_CANDIDATO NUMBER NOT NULL,
  LEGENDA VARCHAR2(20) NOT NULL,
  DATA_HORA TIMESTAMP NOT NULL,
  OBSERVACOES VARCHAR2(255),
  PARECECER_COMP VARCHAR2(255),
  PARECER_TECNICO VARCHAR2(255),
  PRIMARY KEY (ID_ENTREVISTA),
  CONSTRAINT FK_ENT_ID_GEST
    FOREIGN KEY (ID_GESTOR)
      REFERENCES GESTOR(ID_GESTOR),
  CONSTRAINT FK_ENT_ID_CAND
    FOREIGN KEY (ID_CANDIDATO)
      REFERENCES CANDIDATO(ID_CANDIDATO)
);

CREATE TABLE IMAGEM (
  ID_IMAGEM NUMBER ,
  ID_GESTOR NUMBER ,
  ID_CANDIDATO NUMBER ,
  NOME VARCHAR2(255) NOT NULL,
  TIPO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_IMAGEM),
  CONSTRAINT FK_GEST_IMG FOREIGN KEY (ID_GESTOR) REFERENCES GESTOR (ID_GESTOR),
    CONSTRAINT FK_CAND_IMG FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO (ID_CANDIDATO)
);


CREATE SEQUENCE SEQ_GESTOR
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_EDICAO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CANDIDATO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_FORMULARIO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_LINGUAGEM
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CARGO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_PRINT_CONFIG_PC
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ENTREVISTA
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_AVALIACAO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_IMAGEM
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CURRICULO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_INSCRICAO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_TRILHA
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;